popgroup/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('popmania/', include('popmania.urls')),
]

popmania/urls.py
from django.urls import path, include
from . import views

app_name = 'popmania'
urlpatterns = [
    path('', views.index, name='index'),
    path('login_user/', views.login_user,name='login_user'),
    path('authenticate_user/', views.authenticate_user,
    name='authenticate_user'),
    path('register/', views.register,name='register'),
    path('register_user/', views.register_user,
    name='register_user'),
    path('poll/',views.poll, name='poll'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/results', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('logout/',views.logout_user,name='logout'),
]

popmania/models.py
from django.db import models

# Voting question
class Question(models.Model):
    """Class containing the database question table with fields for the question and
      date published for each of the polls

    """
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

def _str_(self):
        """This method will return the relevant question detail from the question record

        :returns: The question detail from the record 

        :rtype: str
        """
        return self.question_text
    
# Selection for votes
class Choice(models.Model):
    """
    Class containing vote table with vote options and tallies linked to each question by
      foreign key
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

def _str_(self):
        """This method will return the choices available for each question record
        
        :returns: Each choice linked to a question

        :rtype: str
        """
        return self.choice_text

popmania/views.py
# L2T23 - Capstone Project Django
# Sources - code snippets used from previous Assignment Tasks L2T18 to L2T23.

from django.shortcuts import get_object_or_404, render
#from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .models import Question, Choice 

# Home page and login to site
def index(request):
    """
        This method will return the web home page for the popgroup
    """
    #template = loader.get_template('popmania/poppythons.html')
    #return HttpResponse(template.render())
    return render(request, 'popmania/poppythons.html')

# Login form
def login_user(request):
    """
        Method to return login page
    """
    return render(request, 'popmania/login.html')

# Page to register new users        
def register(request):
    """
     Method to return register page for new fans
    """
    return render(request, 'popmania/register.html')

# Process to register new users on the database    
def register_user(request):
    """Method to receive login username and password for verification in the database
    
        :raises error_message: User already on the system cannot create

        :returns: object method poll

        :rtype: python object method

    """
    username = request.POST['username']
    password = request.POST['password']
       
    if 'first_name' in request.POST:
        first_name = request.POST['first_name']
    else:
        first_name = ""
    last_name = ""
    email = ""
    
    #Check if user already in the database
    user = authenticate(username=username, password=password)
    if user is None:
        user = User.objects.create_user(
            username,first_name,password,)
        login(request,user)
        return HttpResponseRedirect(reverse('popmania:poll'))
    else:
        # Redisplay the home page
        #return HttpResponseRedirect(reverse('popmania:index'))
        # Redisplay the registering form 
        return render(request, 'popmania/register.html', {
            'error_message': "User already exists."
        })


# authenticate user login to database
def authenticate_user(request):
    """Method to authenticate the user in the database using the python authentication method from
        the django authentication library

        :raises: error_message: Invalid user message from database check

        :returns: object method poll

        :rtype: python object method
    """

    if 'username' in request.POST:
        username = request.POST['username']
    else:
        username = ""
    if 'password' in request.POST:
        password = request.POST['password']
    else:
        password = ""
            
    user = authenticate(username=username, password=password)
        
    if user is None:
        #Return to home page if user login details invalid.
        #return HttpResponseRedirect(reverse('popmania:index'))
        return render(request, 'popmania/login.html', {
            'error_message': "Invalid user credentials."
        })
        
    else:
        login(request,user)
        return HttpResponseRedirect(
            reverse('popmania:poll'))
    
# User logout process
def logout_user(request):
    """Method to logout user from database and display a farewell web page
        :returns: Farewell web page

        :rtype: html
    """
    logout(request)
    return render(request, 'popmania/logout.html')
    #return HttpResponse("Goodbye") 

# Poll page   
def poll(request):
    """Method to display the polls question list for voting

        :returns: Web page with context for option to select a question to vote on
    """
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'popmania/poll.html', context)
    
# Details for voting on given questions
def detail(request, question_id):
    """Method to provide voting details on selected poll

        :param key question_id: The database id for the question record

        :returns: Question detail and voting web page

        :rtype: html
        :rtype: str
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'popmania/detail.html', {'question': question})

# Feedback on voting
def results(request, question_id):
    """Method provides feedback on all polls

        :param str Question: The question in the poll
        :param key question_id: The database id for the question record

        :returns: Results of all the polls

        :rtype: html
        :rtype: list 
    """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'popmania/results.html', {'question': question})
    #return HttpResponse(response)

# Vote on selected question
def vote(request, question_id):
    """Method is to collect votes for the selected poll
        
        :param: question_id key: Database key for the question record

        :raises: keyError: Error raised if no selection is made

        :returns: Input for the method called results
    """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(
            pk=request.POST['choice']
        )
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'popmania/detail.html', {
            'question': question,
            'error_message': "Please select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(
            reverse('popmania:results', args=(question_id,))
        )

popmania/templates/popmania/detail.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->
<html lang="en">
<head>
    <title>Detail</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        body{
            background-color:chartreuse;
            font-family: "Rancho", sans-serif;
            color:rgb(238, 57, 69);
            padding-left: 150px;
        }
</style>
</head>
<body> 
    <!-- Display the select question and voting buttons-->
    <br />
    <h1> {{question.question_text}}</h1>
        {% if error_message %}
            <p class="text-danger"><em><strong>{{error_message}}</strong></em></p>
        {% endif %}

        <form action="{% url 'popmania:vote' question.id %}" method="post">
            {% csrf_token %}

            {% for choice in question.choice_set.all %}
                <h3><input type="radio" name="choice" id="choice {{ forloop.counter }}"
                value="{{ choice.id }}" />
                <label for="choice {{ forloop.counter }}">
                    {{ choice.choice_text }}
                </label></h3>
            
            {% endfor %}
            <button type="submit" class="btn btn-primary mt-3"><h3>Vote</h3></button>
                    
        </form>
        <img src ="{% static 'assets/PopBand1.png' %}" alt = "Thanks for voting!!"  
        class="mx-auto d-block" width="500" height="200">
    </div>
</body>
</html>

popmania/templates/popmania/login.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->
<html lang="en">
<head>
    <title>login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    
    <!--Provide base for formating of text for the whole page and to change the colours of the web urls. -->
    <style>
           
        body{
            background-color:chartreuse;
            font-family: "Rancho", sans-serif;
            color:rgb(238, 57, 69);
            padding-left: 150px;
        }
         /* universal link */     
         a:link {
                color: rgb(0, 195, 255);
            }

        /* visited link */
            a:visited {
                color: purple;
            }

        /* mouse over link */
            a:hover {
                color: rgb(243, 37, 185);
            }

        /* selected link */
            a:active {
                color: rgb(251, 255, 0);
            }
    </style>
</head>

<body>
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h1> Login User </h1>
                <br/><br/>
        
                {% if error_message %}
                    <p class="text-danger"><h2><strong><em>{{error_message}}</strong></em></h2></p>
                    <a href="{% url 'popmania:index' %}"><h4><em><b>Please return to the home page to register if not registered.</b></em></h4></a>
                {% endif %}

                <form action="{% url 'popmania:authenticate_user' %}" method="post">
                    {% csrf_token %}
                    <h2><label>User</label>
                        <input type="text" name="username" placeholder="User" required></h2>
                    <br/><br/>
                    <h2><label>Password</label>
                        <input type="password" name="password" required></h2>
                    <br/><br/>
                    <h2><input type="submit" value="Login" /></h2>
                    <br/><br/>
                </form>
            </div>
            <div class="col">
                <img src ="{% static 'assets/GuitarAndNotes.png' %}" alt = "WELCOME!!"  
                    class="mx-auto d-block" width="500" height="500">
            </div>        
        </div>
    </div>
</body>

</html>

popmania/templates/popmania/logout.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->

<html lang="en">
<!-- Linking up to everything that will help the page look a little more pretty.-->
    <head>
        <title>Logout</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
                integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
                crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
        <Style>
             body{
                background-color:chartreuse;
                font-family: "Rancho", sans-serif;
                color:rgb(238, 57, 69);
                padding-left: 150px;
            }
        </Style>
       
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm ">
                   <h1 class ="display-3"><b>Thank you for visitng our site - see you at the next gig!!</b></h1>
                </div>
            </div>
            <br/><br/>
            <div class="row">
                <div class="col-sm">
                    <img src ="{% static 'assets/NotesAway.png' %}" alt = "Goodbye"  
                        class="mx-auto d-block" width="800" height="300">
                    </div>
                </div>
            </div>
            
    </body>
</html>
        

popmania/templates/popmania/poll.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->
<html lang="en">
<head>
    <title>Polls</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

    <!--Provide base for formating of text for the whole page and to change the colours of the web urls. -->
    <style>
        
        a:link {
            color: rgb(0, 195, 255);
        }

        /* visited link */
        a:visited {
            color: limegreen;
        }

        /* mouse over link */
        a:hover {
        color: aqua;
        }

        /* selected link */
        a:active {
            color: rgb(251, 255, 0);
        }

        .text-font {
             
             font-family: "Rancho", sans-serif;
             color: rgb(181, 112, 206)
         
         }

     </style>
</head>
<body>
    <div class="p-5 bg-light">
        <!-- Display questions for selection to vote on-->
        <div class ="text-font"><h1 class="font-effect-shadow-multiple"><em>Hello Fans, Welcome our Pop Python Polling Site</em></h1>
        <div class="text-font"><h3 class="font-effect-shadow-multiple"><em>Take a vote on our past hits and on our latest song.</em></h3>
        <br />
       
        {% if latest_question_list %}
            {% csrf_token %}
        <ul>
            {% for question in latest_question_list %}
                <li>
                    <h2><a href = "{% url 'popmania:detail' question.id %}">
                        {{ question.question_text }}
                    </h2></a>
                </li>
                
            {% endfor %}
        </ul>
    </div>
        {% else %}
        <p class="text-danger"><h2><b>No polls are available.</b></h2></p>
        {% endif %}
     <br/><br/>   
    <!--Logout when done with voting-->
    <a href = "{% url 'popmania:logout' %}">  <h2><b><div class="ps-5">Logout</b></h2></a> 
</body>
</html>

popmania/templates/popmania/poppythons.html
{% load static %}
<!DOCTYPE html>
    <!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics
     NOTE!! Creator details purposefully left in the snake picture in honour of the person who created this great image.-->
    <html lang="en">
    <head>
        <title>PopMania</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial=-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
            integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
            crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
        <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

        <!--Provide base for formating of text for the whole page and to change the colours of the web urls. -->
        <style>
        body{
                background-color:chartreuse;
                font-family: "Rancho", sans-serif;
                color:rgb(238, 57, 69);
                padding-left: 150px;
            }
         /* universal link */     
         a:link {
                color: rgb(0, 195, 255);
            }

        /* visited link */
            a:visited {
                color: purple;
            }

        /* mouse over link */
            a:hover {
                color: rgb(243, 37, 185);
            }

        /* selected link */
            a:active {
                color: rgb(251, 255, 0);
            }
        </style>
       
    </head>
    </body>
        <!-- Home page for the pop group-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm">
                    <img src ="{% static 'assets/12-2-snake-png-clipart.png' %}" alt = "PopPythons"  
                        class="mx-auto d-block" width="800" height="300">
                    </div>
                </div>
            </div>
            <br/><br/>
            <div class="row">
                <div class="col-sm ">
                   <h1 class ="display-3"><b>You are Rocking With The Pop Pythons!</b></h1>
                </div>
            </div>
            <div class="row">
                <div class="col-sm ">
                    <a href="login_user">
                    <h1>Login to vote on your favourite song and our new hit !!</h1></a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm">
                    <a href = "register" ><h2><b>Or select here to register if new to the site.</b></h2></a>
                </div>
            </div>
            <!--Pictures to fill the page-->
            <div class="row">
                <div class="col-sm">
                    <img src ="{% static 'assets/rock1.png' %}" alt = "PythonMember1"
                        width="120" height= "150"></div>
                <div class="col-sm">
                    <img src ="{% static 'assets/rock2.png' %}" alt = "PythonMember2"
                        width="80" height= "150"></div>
                <div class="col-sm ">
                    <img src ="{% static 'assets/rock3.png' %}" alt = "PythonMember3"
                        width="100" height= "150"></div>
                <div class="col-sm">
                    <img src ="{% static 'assets/rock4.png' %}" alt = "PythonMember4"
                        width="100" height= "150"></div> 
                </div>  
            </div>
        </div>    
    </body>
</html>

popmania/templates/popmania/register.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->
<html lang="en">
<head>
    <title>Register</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!--Provide base for formating of text for the whole page and to change the colours of the web urls. -->
    <style>
        body{
            background-color:chartreuse;
            font-family: "Rancho", sans-serif;
            color:rgb(238, 57, 69);
            padding-left: 150px;
        }
         /* universal link */     
         a:link {
                color: rgb(0, 195, 255);
            }

        /* visited link */
            a:visited {
                color: purple;
            }

        /* mouse over link */
            a:hover {
                color: rgb(243, 37, 185);
            }

        /* selected link */
            a:active {
                color: rgb(251, 255, 0);
            }
    </style>
</head>

<body>
<!--get new user name and password to create a new user in the database-->
    <div class="container mt-3">
        <div class="row">
            <div class="col">
            <br />
                <h1> Register if a new User </h1>
                    {% if error_message %}
                        <p class="text-danger"><h2><em><strong>{{error_message}}</strong></em></h2></p>
                        <a href="{% url 'popmania:index' %}"><h4><em><b>Back to the Home Page?</b></em></h4></a>
                <br/>
                    {% endif %}
                    <form action="{% url 'popmania:register_user' %}" method="post">
                    {% csrf_token %}
                        <h2><label>Username</label>
                            <input type="text" name="username" placeholder="User" required></h2>
                        <br/><br/>
                        <h2><label>Password</label>
                            <input type="password" name="password" required></h2>
                        <br/><br/>
                        <h2><label>Name</label>
                            <input type="text" name="name" placeholder="Name"></h2>
                        <br/><br/>
                        <h2><input type="submit" value="Register" /></h2>
                    </form>
            </div>
            <div class="col">
                <img src ="{% static 'assets/BlueGuitar.png' %}" alt = "Welcome!!"  
                    class="mx-auto d-block" width="500" height="500">
            </div>
        </div>        
    </div>
</body>
</html>

popmania/templates/popmania/results.html
{% load static %}
<!DOCTYPE html>
<!--L2T23 Django V Capstone Project
       Poll new user registration page 
     Sources - thanks to www.w3schools.com and https://docs.djangoproject.com for awesome coding and
      inspiration for everything!
     Code snippets from my previous assignments - L2T18 to 22 Django 1 through to Django v
     and freepngimg.com for the beautiful python and other pics-->

<html lang="en">
<head>
    <title>Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" 
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" 
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Rancho&effect=shadow-multiple">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <!--Provide base for formating of text for the whole page and to change the colours of the web urls. -->
    <style>
            
            body{
            background-color:chartreuse;
            font-family: "Rancho", sans-serif;
            color:rgb(238, 57, 69);
            padding-left: 150px;
        }
         /* universal link */     
         a:link {
                color: rgb(0, 195, 255);
            }

        /* visited link */
            a:visited {
                color: purple;
            }

        /* mouse over link */
            a:hover {
                color: rgb(243, 37, 185);
            }

        /* selected link */
            a:active {
                color: rgb(251, 255, 0);
            }

    </style>
</head>
<!--Display voting results and return to the screen to vote again-->
<body> 
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <br />
                <h2><em> {{question.question_text}} </em></h2>
                <ul>
                    {% for choice in question.choice_set.all %}
                    <li>
                        {% csrf_token %}
                        <h3>{{ choice.choice_text }} -- {{ choice.votes  }}
                        vote{{  choice.votes|pluralize  }}</h3>
                    </li>
                    {% endfor %}
                </ul>
                <br />
                <a href="{% url 'popmania:poll' %}"><h2><em><b>Vote again?</b></em></h2></a>
                
                <!--Logout if done with voting-->
                <a href = "{% url 'popmania:logout' %}"><h2><b><div class="ps-5">Logout here if done voting</b></h2></a> 
            </div>
            <div class="col">
                <img src ="{% static 'assets/LotsOfNotes.png' %}" alt = "Thanks for voting!!"  
                    class="mx-auto d-block" width="400" height="400">
            </div>
            <div class="col">
                <img src ="{% static 'assets/piano.png' %}" alt = "Thanks for voting!!"  
                    class="mx-auto d-block" width="500" height="500">
            </div>
        </div>
    </div>
</body>
</html>